### ISSUE TITLE
Frontend.js has something with a commentsying not needed for final app?

### ISSUE THREAD

**Issue by Joshua-Ronan-Phillips** [liberty-x/lxdata#23]
Frontend.js has something with a comment saying not needed for final app? Perhaps you can get rid of it now?

**Comment by hdrdavies** [comment]
We will defo get rid of this in our final draft :+1:

**Comment by Jbarget** [comment]
Its all gone now, thanks for the heads up
https://github.com/liberty-x/lxdata/pull/33

**Comment by Jbarget** [comment]
@Joshua-Ronan-Phillips feel free to close :)
