### ISSUE TITLE
Top app guys!

### ISSUE THREAD

**Issue by mantagen** [liberty-x/lxdata#29]
Original idea, really nice UI as always!!

Keep it up chaps!! :)))

**Comment by hdrdavies** [comment]
Thanks buddy! 

@RachBLondon @rug1 @Jbarget

**Comment by mantagen** [comment]
Erm... it's usually the decorum for the opener of the issue to close it.

...

**Comment by mantagen** [comment]
@hdrdavies

**Comment by hdrdavies** [comment]
you're absolutely right. Reopened.

**Comment by mantagen** [comment]
Great, thanks.
