### ISSUE TITLE
some normalisation of axes?

### ISSUE THREAD

**Issue by rjmk** [liberty-x/lxdata#31]
It seems most lines have more gates. Maybe you could scale the axes so that they represent the relative frequency of gates, cash machines etc. vs the average

**Comment by hdrdavies** [comment]
Absolutely right, we've had this flagged up in issue [#18](https://github.com/liberty-x/lxdata/issues/18)

**Comment by rjmk** [comment]
:+1:

**Comment by hdrdavies** [comment]
Ta!
